# Generated by Django 4.2.11 on 2024-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_category_remove_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
